from __future__ import annotations

import logging
import math
import typing
from typing import cast

from py_aep.enums import PropertyControlType, PropertyType, PropertyValueType
from py_aep.resolvers.interpolation import interpolate_keyframes

from ...data.units import UNITS_TEXT_MAP
from ...kaitai.descriptors import ChunkField
from ...kaitai.materializer import materialize_property
from ...kaitai.proxy import ProxyBody
from ...kaitai.utils import create_chunk, propagate_check
from ..validators import validate_number, validate_sequence
from .overrides import (
    _ALWAYS_MODIFIED,
    _CANVARY_OVERRIDES,
    _ISSPATIAL_OVERRIDES,
    _NAME_OVERRIDES,
)
from .property_base import PropertyBase
from .specs import _USE_VALUE

if typing.TYPE_CHECKING:
    from typing import Any

    from py_aep.models.properties.marker import MarkerValue
    from py_aep.models.properties.shape import Shape
    from py_aep.models.text.text_document import TextDocument

    from ...kaitai import Aep
    from .keyframe import Keyframe
    from .property_group import PropertyGroup
    from .specs import _PropSpec

logger = logging.getLogger(__name__)

_UNSET = object()  # sentinel for unset min/max fallback

# Match names whose binary values are stored as 0-1 fractions but
# ExtendScript reports as 0-100 percentages.
_PERCENT_MATCH_NAMES: set[str] = {
    "ADBE Opacity",
    "ADBE Scale",
    "ADBE Mask Opacity",
}

_SEPARATION_LEADER = "ADBE Position"
_SEPARATION_FOLLOWERS: list[str] = [
    "ADBE Position_0",
    "ADBE Position_1",
    "ADBE Position_2",
]


def _get_min(prop: Any) -> float | None:
    v = prop.min_value
    return v if isinstance(v, (int, float)) else None


def _get_max(prop: Any) -> float | None:
    v = prop.max_value
    return v if isinstance(v, (int, float)) else None


_NUMERIC_VALUE_TYPES: set[PropertyValueType] = {
    PropertyValueType.OneD,
    PropertyValueType.TwoD,
    PropertyValueType.TwoD_SPATIAL,
    PropertyValueType.ThreeD,
    PropertyValueType.ThreeD_SPATIAL,
    PropertyValueType.COLOR,
}


def _get_dimensions(prop: Any) -> int:
    d: int = prop.dimensions
    # Color properties use dimensions=1 but store 4-element lists.
    if prop._color:
        return 4
    return d


_validate_scalar = validate_number(min=_get_min, max=_get_max)
_validate_list = validate_sequence(length=_get_dimensions, min=_get_min, max=_get_max)


def _validate_value(prop: Property, value: Any) -> None:
    """Validate type, length and bounds of a property value."""
    if value is None:
        return
    if prop.property_value_type not in _NUMERIC_VALUE_TYPES:
        return
    expects_list = prop.dimensions > 1 or prop._color
    if expects_list:
        _validate_list(value, prop)
    else:
        _validate_scalar(value, prop)


def _values_equal(a: Any, b: Any) -> bool:
    """Compare two property values with float tolerance.

    Handles scalars, lists/tuples, booleans, and None.
    Uses [math.isclose][] for numeric comparisons.
    """
    if a is None or b is None:
        return a is b
    if isinstance(a, bool) or isinstance(b, bool):
        return bool(a == b)
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        if len(a) != len(b):
            return False
        return all(_values_equal(x, y) for x, y in zip(a, b))
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return math.isclose(a, b, abs_tol=1e-6)
    return bool(a == b)


class Property(PropertyBase):
    """
    The `Property` object contains value, keyframe, and expression information
    about a particular AE property of a layer. An AE property is a value,
    often animatable, of an effect, mask, or transform within an individual
    layer.

    Example:
        ```python
        from py_aep import parse

        app = parse("project.aep")
        comp = app.project.compositions[0]
        prop = comp.layers[0].transform.property("ADBE Position")
        print(prop.value)
        ```

    Info:
        `Property` is a subclass of [PropertyBase][]. All methods and attributes
        of [PropertyBase][] are available when working with `Property`.

    See: https://ae-scripting.docsforadobe.dev/property/property/
    """

    keyframes: list[Keyframe]
    """The list of keyframes for this property. Read-only."""

    default_value: Any
    """The default value of the property."""

    dimensions = ChunkField[int](
        "_tdb4",
        "dimensions",
        default=1,
    )
    """The number of dimensions in the property value (1, 2, 3, or 4). Read-only."""

    expression_error: str
    """Contains the error, if any, generated by evaluation of the string
    most recently set in [expression][]. If no expression string has been
    specified, or if the last expression string evaluated without error,
    contains the empty string (`""`).

    Warning:
        The parser cannot evaluate expressions, so this attribute is
        always an empty string. After Effects computes expression errors
        at runtime when it evaluates the expression engine; this
        information is not stored in the binary `.aep` file.
    Read-only."""

    last_value: Any
    """The last value of the property (before animation)."""

    nb_options: int | None
    """The number of options in a dropdown property."""

    property_parameters: list[str] | None
    """An array of all item strings in a dropdown menu property. This
    attribute applies to dropdown menu properties of effects and layers,
    including custom strings in the Menu property of the Dropdown Menu
    Control. Read-only."""

    _animated = ChunkField.bool("_tdb4", "animated", default=False)

    _color = ChunkField.bool("_tdb4", "color", default=False)

    _integer = ChunkField.bool("_tdb4", "integer", default=False)

    _no_value = ChunkField.bool("_tdb4", "no_value", default=False)

    _vector = ChunkField.bool("_tdb4", "vector", default=False)

    locked_ratio = ChunkField.bool(
        "_tdsb", "locked_ratio", read_only=True, default=False
    )
    """When `True`, the property's X/Y ratio is locked. Read-only."""

    _is_spatial_raw = ChunkField.bool("_tdb4", "is_spatial", default=False)

    @property
    def is_spatial(self) -> bool:
        """When `True`, the named property defines a spatial value.

        Examples are position and effect point controls. Read-only.
        """
        override = _ISSPATIAL_OVERRIDES.get(self.match_name)
        if override is not None:
            return override
        return bool(self._is_spatial_raw)

    @property
    def name(self) -> str:
        """Display name of the property. Read / Write."""
        override = _NAME_OVERRIDES.get(self.match_name)
        if override is not None:
            return override
        base_name: str = PropertyBase.name.fget(self)  # type: ignore[attr-defined]
        # NO_VALUE effect properties that store the match_name in tdsn
        # are unnamed separators/group headers - ExtendScript returns "".
        if (
            self.property_value_type == PropertyValueType.NO_VALUE
            and base_name == self.match_name
            and self._is_in_effect()
        ):
            return ""
        return base_name

    @name.setter
    def name(self, value: str) -> None:
        PropertyBase.name.fset(self, value)  # type: ignore[attr-defined]

    @classmethod
    def synthesized(
        cls,
        spec: _PropSpec,
        property_depth: int,
        *,
        parent_property: PropertyGroup,
        value: Any = _USE_VALUE,
        default_value: Any = _USE_VALUE,
    ) -> Property:
        """Create a synthesized Property from a `_PropSpec`.

        Used to synthesize properties expected by ExtendScript but absent
        from the binary.

        Args:
            spec: The property specification describing the property.
            property_depth: The depth of the property in the tree.
            parent_property: The container that owns the synthesized property.
            value: Override for the property value. When omitted, uses
                `spec.value`.
            default_value: Override for the default value. When omitted,
                uses the spec's `default_value` logic.
        """
        final_value = spec.value if value is _USE_VALUE else value
        no_value = spec.pvt == PropertyValueType.NO_VALUE
        if spec.can_vary_over_time is not None:
            can_vary = spec.can_vary_over_time
        else:
            can_vary = not no_value
        prop = cls(
            _tdsb=ProxyBody(
                enabled=1,
                locked_ratio=0,
                roto_bezier=0,
                dimensions_separated=0,
            ),
            _tdb4=ProxyBody(
                dimensions=spec.dimensions,
                is_spatial=int(spec.is_spatial),
                animated=0,
                color=int(spec.color),
                integer=0,
                no_value=int(no_value),
                vector=int(spec.dimensions > 1),
                can_vary_over_time=int(can_vary),
                expression_disabled=1,
            ),
            keyframes=[],
            match_name=spec.match_name,
            auto_name=spec.auto_name,
            parent_property=parent_property,
            property_control_type=PropertyControlType.UNKNOWN,
            property_depth=property_depth,
            property_value_type=spec.pvt,
            value=final_value,
        )
        if default_value is not _USE_VALUE:
            prop.default_value = default_value
        else:
            prop.default_value = (
                final_value if spec.default_value is _USE_VALUE else spec.default_value
            )
        if spec.min_value is not None:
            prop._min_value_fallback = spec.min_value
        if spec.max_value is not None:
            prop._max_value_fallback = spec.max_value
        return prop

    def __init__(
        self,
        *,
        _tdsb: Aep.TdsbBody | None = None,
        _tdb4: Aep.Tdb4Body | None = None,
        _expression_utf8: Aep.Utf8Body | None = None,
        _name_utf8: Aep.Utf8Body | None = None,
        _tdbs: Aep.ListBody | None = None,
        _tdum: Aep.TdumBody | None = None,
        _tduM: Aep.TdumBody | None = None,
        _cdat: Aep.CdatBody | None = None,
        parent_property: PropertyGroup | None = None,
        match_name: str,
        property_depth: int,
        auto_name: str | None = None,
        keyframes: list[Keyframe],
        value: Any,
        expression_enabled: bool | None = None,
        expression: str | None = None,
        property_control_type: PropertyControlType | None = None,
        property_value_type: PropertyValueType | None = None,
        dimensions_separated: bool | None = None,
        units_text: str | None = None,
        can_vary_over_time: bool | None = None,
    ) -> None:
        super().__init__(
            _tdsb=_tdsb,
            _name_utf8=_name_utf8,
            parent_property=parent_property,
            match_name=match_name,
            auto_name=auto_name,
            property_depth=property_depth,
        )
        self._tdb4 = _tdb4
        self._expression_utf8 = _expression_utf8
        self._tdbs = _tdbs
        self._tdum = _tdum
        self._tduM = _tduM
        self._cdat = _cdat

        self._can_vary_over_time = can_vary_over_time

        self._dimensions_separated = dimensions_separated

        self._expression_enabled = expression_enabled
        self._expression = expression

        self.keyframes = keyframes
        self._link_keyframes()

        self._property_control_type = property_control_type

        self._property_value_type = property_value_type

        self._value: Any = value

        self._units_text = units_text

        self.default_value = None

        self.expression_error = ""

        self.last_value = None

        self._min_value_fallback: Any = _UNSET
        self._max_value_fallback: Any = _UNSET
        self._scale_z_override: float | None = None

        self.nb_options = None

        self.property_parameters = None

        self._property_type = PropertyType.PROPERTY

    @property
    def _speed_factor(self) -> float:
        """Speed unit factor for ease objects: 100 for percent properties."""
        if self.match_name in _PERCENT_MATCH_NAMES:
            return 100.0
        return 1.0

    def _link_keyframes(self) -> None:
        """Set back-references on keyframes after construction.

        Each keyframe gets a reference to its owning property and to its
        prev/next neighbours for lazy ease computation.
        """
        for i, kf in enumerate(self.keyframes):
            kf._bind_property(self)
            if i > 0:
                kf._prev = self.keyframes[i - 1]
            if i < len(self.keyframes) - 1:
                kf._next = self.keyframes[i + 1]

    def _ensure_materialized(self) -> None:
        """Replace ProxyBody backing with real Kaitai chunks.

        Called automatically by `__setattr__` on first end-user write
        to a synthesized property. After this method, the property is
        indistinguishable from one that was parsed from binary.
        """
        if not isinstance(self._tdsb, ProxyBody):
            return

        parent = self.parent_property
        if parent is None:
            return

        # Ensure the parent group is materialized first.
        parent._ensure_materialized()

        tdgp = parent._tdgp
        if tdgp is None:
            return

        result = materialize_property(
            tdgp,
            self.match_name,
            self._tdsb,
            self._tdb4,
            self._value,
            display_name=self._name,
        )

        # Use object.__setattr__ to bypass __setattr__ materialization guard.
        object.__setattr__(self, "_tdsb", result.tdsb)
        object.__setattr__(self, "_tdb4", result.tdb4)
        object.__setattr__(self, "_tdbs", result.tdbs)
        object.__setattr__(self, "_name_utf8", result.name_utf8)
        if result.cdat is not None:
            object.__setattr__(self, "_cdat", result.cdat)

    @staticmethod
    def _read_tdum(body: Aep.TdumBody) -> Any:
        """Extract value from a tdum/tduM chunk body."""
        if body.is_color:
            return list(body.value_color)
        if body.is_integer:
            return body.value_integer  # type: ignore[return-value]
        value = list(body.value_doubles)
        if len(value) == 1:
            return value[0]
        return value

    def _read_cdat_raw(self) -> Any:
        """Read the raw value from the cdat chunk body.

        Returns a scalar for 1D non-color properties, a list for
        multi-dimensional or color properties, or `None` when the
        chunk has no data.
        """
        if self._cdat is None:
            return None
        values = self._cdat.value[: self.dimensions]
        if not values:
            return None
        if self.dimensions == 1 and not self._color:
            return values[0]
        return values

    def _resolve_value(self, raw: Any) -> Any:
        """Forward-transform a raw binary value to user-facing units.

        Applied in order: percent scaling, color conversion, effect point
        denormalization.
        """
        if raw is None:
            return None
        # 1. Percent scaling (0-1 fraction -> 0-100 percentage)
        if self.match_name in _PERCENT_MATCH_NAMES:
            if isinstance(raw, (int, float)):
                raw = raw * 100.0
            elif isinstance(raw, list):
                raw = [v * 100.0 for v in raw]
            # For 2D layers, Z-Scale is stored as 0.01 in the binary
            # (irrelevant axis). ES always normalizes it to 100.
            if (
                self._scale_z_override is not None
                and isinstance(raw, list)
                and len(raw) >= 3
            ):
                raw[2] = self._scale_z_override
        # 2. Color (ARGB 0-255 -> RGBA 0-1)
        if self._color:
            if isinstance(raw, list) and len(raw) == 4:
                a, r, g, b = raw
                raw = [r / 255.0, g / 255.0, b / 255.0, a / 255.0]
        # 3. Effect point (0-1 fraction -> pixel coordinates)
        if self._effect_scale is not None:
            if isinstance(raw, list) and len(raw) >= 2:
                raw = [v * s for v, s in zip(raw, self._effect_scale)]
        return raw

    def _unresolve_value(self, value: Any) -> Any:
        """Reverse-transform a user-facing value to raw binary units.

        Applied in reverse order: effect point normalization, color
        conversion, then percent scaling.
        """
        if value is None:
            return None
        if not isinstance(value, (int, float, list)):
            return value
        if isinstance(value, list) and value and not isinstance(value[0], (int, float)):
            return value
        # 3. Reverse effect point (pixel coordinates -> 0-1 fraction)
        if self._effect_scale is not None:
            if isinstance(value, list) and len(value) >= 2:
                value = [v / s if s else 0.0 for v, s in zip(value, self._effect_scale)]
        # 2. Reverse color (RGBA 0-1 -> ARGB 0-255)
        if self._color:
            if isinstance(value, list) and len(value) == 4:
                r, g, b, a = value
                value = [a * 255.0, r * 255.0, g * 255.0, b * 255.0]
        # 1. Reverse percent (0-100 -> 0-1 fraction)
        if self.match_name in _PERCENT_MATCH_NAMES:
            if isinstance(value, (int, float)):
                value = value / 100.0
            elif isinstance(value, list):
                value = [v / 100.0 for v in value]
        return value

    def _write_cdat(self, value: Any) -> None:
        """Write a user-facing value to the cdat chunk body.

        Applies `_unresolve_value` to convert back to raw binary units
        before writing.
        """
        if self._cdat is None:
            return
        if not isinstance(value, (int, float, list)):
            return
        if isinstance(value, list) and value and not isinstance(value[0], (int, float)):
            return
        raw_value = self._unresolve_value(value)
        raw = list(self._cdat.value)
        if isinstance(raw_value, list):
            raw[: len(raw_value)] = raw_value
        else:
            raw[0] = raw_value
        if self._cdat.is_le:
            self._cdat.value_le = raw
        else:
            self._cdat.value_be = raw
        self._cdat._invalidate_value()
        propagate_check(self._cdat)

    @property
    def value(self) -> Any:
        """
        The value of the named property at the current time. If
        `expression_enabled` is `True`, returns the evaluated expression
        value. If there are keyframes, returns the keyframed value at the
        current time. Otherwise, returns the static value. Read / Write.
        """
        if self._value is not None:
            return self._value
        if self._cdat is not None:
            return self._resolve_value(self._read_cdat_raw())
        if self.keyframes:
            return self.keyframes[0].value
        return None

    @value.setter
    def value(self, value: Any) -> None:
        self._ensure_materialized()
        _validate_value(self, value)
        self._value = value
        self._write_cdat(value)

    @property
    def min_value(self) -> Any:
        """
        The minimum permitted value of the named property. Only valid if
        `has_min` is `True`. Read-only.
        """
        if self._min_value_fallback is not _UNSET:
            return self._min_value_fallback
        if self._tdum is not None:
            return self._read_tdum(self._tdum)
        return None

    @property
    def max_value(self) -> Any:
        """
        The maximum permitted value of the named property. Only valid if
        `has_max` is `True`. Read-only.
        """
        if self._max_value_fallback is not _UNSET:
            return self._max_value_fallback
        if self._tduM is not None:
            return self._read_tdum(self._tduM)
        return None

    @property
    def units_text(self) -> str:
        """
        The text description of the units in which the value is expressed.

        Common values include `"pixels"`, `"degrees"`, `"percent"`,
        `"seconds"`, and `"dB"`. An empty string indicates the property
        has no specific unit. Read-only.
        """
        if self._units_text is not None:
            return self._units_text
        return UNITS_TEXT_MAP.get(self.match_name, "")

    @property
    def can_vary_over_time(self) -> bool:
        """
        When `True`, the named property can vary over time - that is, keyframe
        values or expressions can be written to this property.

        Note:
            A small subset of effect dropdown / menu parameters may report
            `can_vary_over_time` as `False` in the binary even though After
            Effects allows keyframing them.
        Read-only.
        """
        if self._can_vary_over_time is not None:
            return self._can_vary_over_time
        if self.match_name in _CANVARY_OVERRIDES:
            return _CANVARY_OVERRIDES[self.match_name]
        if self._tdb4 is not None:
            # NO_VALUE properties always report canVaryOverTime=True in AE,
            # even though the binary byte says otherwise.
            return bool(self._tdb4.can_vary_over_time or self._no_value)
        return False

    @property
    def dimensions_separated(self) -> bool:
        """
        When `True`, the property's dimensions are represented as separate
        properties. For example, if the layer's position is represented as X
        Position and Y Position properties in the Timeline panel, the Position
        property has this attribute set to `True`. This attribute applies only
        when the property is a "separation leader" (a multidimensional property
        that can be separated). Read / Write.
        """
        if self._dimensions_separated is not None:
            return self._dimensions_separated
        if self.match_name == "ADBE Position" and self._tdsb is not None:
            # Light and Camera layers always have 3D position but do not
            # expose dimensionsSeparated in ExtendScript.
            layer = self._containing_layer
            if layer is not None and layer._ldta.layer_type.name in (
                "light",
                "camera",
            ):
                return False
            return bool(self._tdsb.dimensions_separated)
        return False

    @dimensions_separated.setter
    def dimensions_separated(self, value: bool) -> None:
        self._ensure_materialized()
        self._dimensions_separated = value
        if self.match_name == _SEPARATION_LEADER and self._tdsb is not None:
            self._tdsb.dimensions_separated = int(value)
            if not isinstance(self._tdsb, ProxyBody):
                propagate_check(self._tdsb)

    @property
    def expression(self) -> str:
        """
        The expression for the named property. Writeable only when
        `can_set_expression` for the named property is `True`.
        Read / Write.
        """
        if self._expression is not None:
            return self._expression
        if self._expression_utf8 is not None:
            text: str = self._expression_utf8.contents
            return text.split("\x00")[0]
        return ""

    @expression.setter
    def expression(self, value: str) -> None:
        self._ensure_materialized()
        self._expression = value
        if self._expression_utf8 is None and self._tdbs is not None:
            chunk = create_chunk(self._tdbs, "Utf8", "Utf8Body", contents=value)
            self._expression_utf8 = chunk.body
        elif self._expression_utf8 is not None:
            self._expression_utf8.contents = value
            propagate_check(self._expression_utf8)

    @property
    def expression_enabled(self) -> bool:
        """
        When `True`, the named property uses its associated expression to
        generate a value. When `False`, the keyframe information or static
        value of the property is used. Read / Write.
        """
        if self._expression_enabled is not None:
            return self._expression_enabled
        if self._tdb4 is not None:
            disabled = getattr(self._tdb4, "expression_disabled", True)
            return not disabled and bool(self.expression)
        return False

    @expression_enabled.setter
    def expression_enabled(self, value: bool) -> None:
        self._ensure_materialized()
        self._expression_enabled = value
        if self._tdb4 is not None and not isinstance(self._tdb4, ProxyBody):
            self._tdb4.expression_disabled = not value
            propagate_check(self._tdb4)

    @property
    def property_control_type(self) -> PropertyControlType:
        """The control type of the property (e.g., scalar, color, boolean). Read-only."""
        if self._property_control_type is not None:
            return self._property_control_type
        pct, _ = self._determine_property_types()
        return pct

    @property
    def property_value_type(self) -> PropertyValueType:
        """
        The type of value stored in the named property. Each type of data is
        stored and retrieved in a different kind of structure. For example,
        a 3D spatial property (such as a layer's position) is stored as an
        array of three floating-point values. Read-only.
        """
        if self._property_value_type is not None:
            return self._property_value_type
        _, pvt = self._determine_property_types()
        return pvt

    def _determine_property_types(
        self,
    ) -> tuple[PropertyControlType, PropertyValueType]:
        """Determine property control and value types from tdb4 flags."""
        pct = PropertyControlType.UNKNOWN
        pvt = PropertyValueType.UNKNOWN

        if self._no_value:
            pvt = PropertyValueType.NO_VALUE
        if self._color:
            pct = PropertyControlType.COLOR
            pvt = PropertyValueType.COLOR
        elif self._integer and self.dimensions <= 1:
            pct = PropertyControlType.BOOLEAN
            pvt = PropertyValueType.OneD
        elif self._vector or (self._integer and self.dimensions > 1):
            if self.dimensions == 1:
                pct = PropertyControlType.SCALAR
                pvt = PropertyValueType.OneD
            elif self.dimensions == 2:
                pct = PropertyControlType.TWO_D
                pvt = (
                    PropertyValueType.TwoD_SPATIAL
                    if self.is_spatial
                    else PropertyValueType.TwoD
                )
            elif self.dimensions == 3:
                pct = PropertyControlType.THREE_D
                pvt = (
                    PropertyValueType.ThreeD_SPATIAL
                    if self.is_spatial
                    else PropertyValueType.ThreeD
                )

        if pct == PropertyControlType.UNKNOWN:
            logger.warning(
                "Could not determine type for property %s"
                " | dimensions: %s"
                " | integer: %s"
                " | is_spatial: %s"
                " | vector: %s"
                " | no_value: %s"
                " | color: %s",
                self.match_name,
                self.dimensions,
                self._integer,
                self.is_spatial,
                self._vector,
                self._no_value,
                self._color,
            )

        return pct, pvt

    @property
    def is_separation_leader(self) -> bool:
        """`True` if the property is a multidimensional property that
        can be separated.
        """
        return self.match_name == _SEPARATION_LEADER

    @property
    def is_separation_follower(self) -> bool:
        """`True` if the property is a component of a separated
        multidimensional property (e.g. X Position, Y Position,
        Z Position).
        """
        return self.match_name in _SEPARATION_FOLLOWERS

    @property
    def separation_dimension(self) -> int | None:
        """For a separated follower, the dimension it represents.

        Returns 0, 1, or 2 for X, Y, or Z. Returns `None` for
        properties that are not separation followers.
        """
        if not self.is_separation_follower:
            return None
        return _SEPARATION_FOLLOWERS.index(self.match_name)

    @property
    def separation_leader(self) -> Property | None:
        """For a separation follower, the leader property.

        Returns the [Property][] that acts as the separation leader
        (e.g. Position) for this follower (e.g. X Position).
        Returns `None` when this property is not a follower or the
        leader cannot be found.
        """
        if self.match_name not in _SEPARATION_FOLLOWERS:
            return None
        parent = self.parent_property
        if parent is None or not hasattr(parent, "properties"):
            return None
        return cast("Property | None", parent.property(_SEPARATION_LEADER))

    def get_separation_follower(self, dim: int) -> Property | None:
        """
        Retrieve a specific follower property for a separated,
        multidimensional property.

        For example, you can use this method on the Position property
        to access the separated X Position and Y Position properties.

        Args:
            dim: The dimension number (starting at 0).
        """
        if not self.is_separation_leader:
            return None
        parent = self.parent_property
        if parent is None or not hasattr(parent, "properties"):
            return None
        if dim < 0 or dim >= len(_SEPARATION_FOLLOWERS):
            raise ValueError(
                f"dim must be in range [0, {len(_SEPARATION_FOLLOWERS) - 1}], got {dim}"
            )
        match_name = _SEPARATION_FOLLOWERS[dim]
        return cast("Property | None", parent.property(match_name))

    def nearest_key_index(self, time: float) -> int:
        """
        Returns the index of the keyframe nearest to the specified time.

        Args:
            time: The time in seconds; a floating-point value. The beginning
                of the composition is 0.
        """
        return min(
            range(len(self.keyframes)),
            key=lambda i: abs(self.keyframes[i].frame_time - time),
        )

    def nearest_key(self, time: float) -> Keyframe:
        """
        Returns the keyframe nearest to the specified time.

        Args:
            time: The time in seconds; a floating-point value. The beginning
                of the composition is 0.
        """
        index = self.nearest_key_index(time)
        return self.keyframes[index]

    @property
    def is_modified(self) -> bool:
        """`True` if the property value differs from its default.

        A property is considered modified when it has keyframes, has an
        expression (enabled or disabled), or when its current value
        differs from `default_value`.
        """
        if self._animated:
            return True
        if self.expression:
            return True
        # Source Text has no meaningful default - always modified when it
        # has a value (text is always user-authored).
        if self.match_name == "ADBE Text Document" and self.value is not None:
            return True
        # NO_VALUE (button/separator/group header) properties inside effects
        # are always reported as modified in ExtendScript.
        if self.property_value_type == PropertyValueType.NO_VALUE:
            return self._is_in_effect()
        # Mask reference properties that exist in the binary are always
        # modified - their presence indicates user interaction even when
        # the value is 0 (no mask).  Synthesized default slots (ProxyBody)
        # remain unmodified.
        if (
            self.property_value_type == PropertyValueType.MASK_INDEX
            and self._is_in_effect()
            and not isinstance(self._tdsb, ProxyBody)
        ):
            return True
        if self.match_name in _ALWAYS_MODIFIED:
            return True
        if self.default_value is not None:
            return not _values_equal(self.value, self.default_value)
        # Effect properties with no known default are considered modified
        # when they have a value - ExtendScript treats the absence of a
        # default as "always modified".  LAYER_INDEX is excluded because
        # its binary default (0 = "None" layer) is not stored in pard;
        # layer references should report False when unset.
        if (
            self.value is not None
            and self._is_in_effect()
            and self.property_value_type != PropertyValueType.LAYER_INDEX
        ):
            return True
        return False

    @property
    def is_dropdown_effect(self) -> bool:
        """`True` if the property is the Menu property of a Dropdown Menu Control effect."""
        return self._property_control_type == PropertyControlType.ENUM

    @property
    def is_time_varying(self) -> bool:
        """`True` if the named property has keyframes or an enabled expression."""
        return bool((self.expression and self.expression_enabled) or self._animated)

    @property
    def has_max(self) -> bool:
        """`True` if there is a maximum permitted value for the named property."""
        return self.max_value is not None

    @property
    def has_min(self) -> bool:
        """`True` if there is a minimum permitted value for the named property."""
        return self.min_value is not None

    def value_at_time(
        self, time: float, pre_expression: bool = True
    ) -> list[float] | float | MarkerValue | Shape | TextDocument | None:
        """Get the value of the named property at the given time.

        If the property has keyframes, the value is computed by
        interpolating between surrounding keyframes using the stored
        interpolation type and temporal ease.

        If the property is not animated, returns the static
        [value][Property.value].

        Args:
            time: The composition time in seconds at which to evaluate
                the property.
            pre_expression: When `True` the value is evaluated before
                any expression is applied (the only mode supported by
                the parser).

        Raises:
            NotImplementedError: If *pre_expression* is `False`,
                because the parser cannot evaluate expressions.
        """
        if not pre_expression:
            raise NotImplementedError(
                "Expression evaluation is not supported by the parser."
            )
        if not self.keyframes:
            return self.value  # type: ignore[no-any-return]

        return interpolate_keyframes(time, self.keyframes, self.is_spatial)

    @property
    def _frame_offset(self) -> int:
        """Frame offset for converting layer-relative keyframe times to comp time.

        The binary stores keyframe times relative to the layer's start.
        ExtendScript reports them in composition time.  This property
        lazily computes the offset from the containing layer's start_time
        and composition frame rate.
        """
        layer = self._containing_layer
        if layer is None:
            return 0
        start_time: float = layer._ldta.start_time
        if start_time == 0.0:
            return 0
        result: int = round(start_time * layer.containing_comp.frame_rate)
        return result

    @property
    def _effect_scale(self) -> list[float] | None:
        """Scale factors for denormalizing 0-1 binary values to pixel coordinates.

        Lazily computed from context:
        - Effect point properties (TWO_D inside an effect): composition
          dimensions.
        - Anchor Point: layer source dimensions.
        - All others: `None`.

        On first access for effect points, also triggers
        `_scale_effect_point_speeds` to set speed factors on keyframe ease
        objects.
        """
        _sentinel = "_effect_scale"
        # Allow explicit override via __dict__ (e.g. from tests or
        # _scale_effect_point_speeds recursion guard).
        if _sentinel in self.__dict__:
            result: list[float] | None = self.__dict__[_sentinel]
            return result

        scale: list[float] | None = None

        if self.match_name == "ADBE Anchor Point":
            layer = self._containing_layer
            if layer is not None:
                width = getattr(layer, "width", 0)
                height = getattr(layer, "height", 0)
                if width and height:
                    scale = [float(width), float(height), 1.0]
        elif (
            self._property_control_type == PropertyControlType.TWO_D
            and self._is_in_effect()
        ):
            layer = self._containing_layer
            if layer is not None:
                comp = layer.containing_comp
                scale = [float(comp.width), float(comp.height)]

        if scale is not None and self.match_name != "ADBE Anchor Point":
            # Set guard before _scale_effect_point_speeds (which accesses
            # kf.value -> _resolve_value -> _effect_scale) to avoid recursion.
            self.__dict__[_sentinel] = scale
            try:
                self._scale_effect_point_speeds(scale)
            finally:
                del self.__dict__[_sentinel]
        return scale

    @_effect_scale.setter
    def _effect_scale(self, value: list[float] | None) -> None:
        self.__dict__["_effect_scale"] = value

    def _scale_effect_point_speeds(self, scale: list[float]) -> None:
        """Set speed factor on BEZIER ease objects for effect point properties.

        The binary stores speed in normalized (0-1) units per second.
        ExtendScript reports speed in pixel units per second.  The factor
        depends on the direction of motion between adjacent keyframes and
        is stored on each `KeyframeEase._speed_factor` for lazy application.
        """
        n = len(self.keyframes)
        for i, kf in enumerate(self.keyframes):
            for ease_list, other_idx in [
                (kf._out_temporal_ease, i + 1),
                (kf._in_temporal_ease, i - 1),
            ]:
                if not ease_list or other_idx < 0 or other_idx >= n:
                    continue
                other_kf = self.keyframes[other_idx]
                val_a = kf.value
                val_b = other_kf.value
                if (
                    not isinstance(val_a, list)
                    or not isinstance(val_b, list)
                    or len(val_a) < 2
                    or len(val_b) < 2
                ):
                    continue
                delta_px = [b - a for a, b in zip(val_a, val_b)]
                delta_norm = [d / s if s else 0.0 for d, s in zip(delta_px, scale)]
                dist_px = math.sqrt(sum(d * d for d in delta_px))
                dist_norm = math.sqrt(sum(d * d for d in delta_norm))
                if dist_norm == 0:
                    continue
                factor = dist_px / dist_norm
                for ease in ease_list:
                    ease._speed_factor = factor
