"""py_aep - A .aep (After Effects Project) parser."""

from __future__ import annotations

import os

try:
    from importlib.metadata import PackageNotFoundError, version
except ImportError:
    from importlib_metadata import (  # type: ignore[import,no-redef]  # Python 3.7
        PackageNotFoundError,
        version,
    )

from .enums import (
    AlphaMode,
    AudioBitDepth,
    AudioChannels,
    AudioSampleRate,
    AutoKernType,
    AutoOrientType,
    BaselineDirection,
    BitsPerChannel,
    BlendingMode,
    BoxAutoFitPolicy,
    BoxFirstBaselineAlignment,
    BoxVerticalAlignment,
    ChannelType,
    CloseOptions,
    ColorDepthSetting,
    ColorManagementSystem,
    ComposerEngine,
    CTFontTechnology,
    CTFontType,
    CTScript,
    DigitSet,
    DiskCacheSetting,
    EffectsSetting,
    FastPreviewType,
    FeetFramesFilmType,
    FieldRender,
    FieldSeparationType,
    FillLightingCorrectionType,
    FillMethodType,
    FillOutputDepthType,
    FillRangeType,
    FontBaselineOption,
    FontCapsOption,
    FootageTimecodeDisplayStartType,
    FrameBlendingSetting,
    FrameBlendingType,
    FrameRateSetting,
    FramesCountType,
    GetSettingsFormat,
    GpuAccelType,
    GuideLayers,
    GuideOrientationType,
    ImportAsType,
    KeyframeInterpolationType,
    Label,
    Language,
    LayerQuality,
    LayerSamplingQuality,
    LeadingType,
    LightType,
    LinearLightMode,
    LineJoinType,
    LineOrientation,
    LogType,
    LoopMode,
    LutInterpolationMethod,
    MaskFeatherFalloff,
    MaskMode,
    MaskMotionBlur,
    MotionBlurSetting,
    OutputAudio,
    OutputChannels,
    OutputColorDepth,
    OutputColorMode,
    OutputFormat,
    ParagraphDirection,
    ParagraphJustification,
    PlayMode,
    PostRenderAction,
    PREFType,
    ProjectThread,
    PropertyControlType,
    PropertyType,
    PropertyValueType,
    ProxyUseSetting,
    PulldownMethod,
    PulldownPhase,
    PulldownSetting,
    PurgeTarget,
    RenderQuality,
    ResizeQuality,
    ResolveType,
    RQItemStatus,
    SoloSwitchesSetting,
    TimeDisplayType,
    TimeSpanSource,
    ToolType,
    TrackMatteType,
    ViewerType,
)
from .kaitai import Aep
from .models import (
    Application,
    AVItem,
    AVLayer,
    CameraLayer,
    CineonFormatOptions,
    CompItem,
    FeatherPoint,
    FileSource,
    FolderItem,
    FontObject,
    FootageItem,
    FootageSource,
    Guide,
    Item,
    JpegFormatOptions,
    Keyframe,
    KeyframeEase,
    Layer,
    LightLayer,
    MarkerValue,
    MaskPropertyGroup,
    OpenExrFormatOptions,
    OutputModule,
    PlaceholderSource,
    PngFormatOptions,
    Project,
    Property,
    PropertyBase,
    PropertyGroup,
    RenderQueue,
    RenderQueueItem,
    SettingsView,
    Shape,
    ShapeLayer,
    SolidSource,
    TargaFormatOptions,
    TextDocument,
    TextLayer,
    ThreeDModelLayer,
    TiffFormatOptions,
    View,
    Viewer,
    ViewOptions,
    XmlFormatOptions,
)

try:
    __version__ = version("py_aep")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "__version__",
    "AlphaMode",
    "Application",
    "AudioBitDepth",
    "AudioChannels",
    "AudioSampleRate",
    "AutoKernType",
    "AutoOrientType",
    "AVItem",
    "AVLayer",
    "BaselineDirection",
    "BitsPerChannel",
    "BlendingMode",
    "BoxAutoFitPolicy",
    "BoxFirstBaselineAlignment",
    "BoxVerticalAlignment",
    "CameraLayer",
    "ChannelType",
    "CineonFormatOptions",
    "CloseOptions",
    "ColorDepthSetting",
    "ColorManagementSystem",
    "CompItem",
    "ComposerEngine",
    "CTFontTechnology",
    "CTFontType",
    "CTScript",
    "DigitSet",
    "DiskCacheSetting",
    "EffectsSetting",
    "FastPreviewType",
    "FeatherPoint",
    "FeetFramesFilmType",
    "FieldRender",
    "FieldSeparationType",
    "FileSource",
    "FillLightingCorrectionType",
    "FillMethodType",
    "FillOutputDepthType",
    "FillRangeType",
    "FolderItem",
    "FontBaselineOption",
    "FontCapsOption",
    "FontObject",
    "FootageItem",
    "FootageSource",
    "FootageTimecodeDisplayStartType",
    "FrameBlendingSetting",
    "FrameBlendingType",
    "FrameRateSetting",
    "FramesCountType",
    "GetSettingsFormat",
    "GpuAccelType",
    "GuideOrientationType",
    "GuideLayers",
    "Guide",
    "ImportAsType",
    "Item",
    "JpegFormatOptions",
    "Keyframe",
    "KeyframeEase",
    "KeyframeInterpolationType",
    "Label",
    "Language",
    "Layer",
    "LayerQuality",
    "LayerSamplingQuality",
    "LeadingType",
    "LightLayer",
    "LightType",
    "LinearLightMode",
    "LineJoinType",
    "LineOrientation",
    "LogType",
    "LoopMode",
    "LutInterpolationMethod",
    "MarkerValue",
    "MaskFeatherFalloff",
    "MaskMode",
    "MaskMotionBlur",
    "MaskPropertyGroup",
    "MotionBlurSetting",
    "OpenExrFormatOptions",
    "OutputAudio",
    "OutputChannels",
    "OutputColorDepth",
    "OutputColorMode",
    "OutputFormat",
    "OutputModule",
    "ParagraphDirection",
    "ParagraphJustification",
    "parse",
    "PlaceholderSource",
    "PlayMode",
    "PngFormatOptions",
    "PostRenderAction",
    "PREFType",
    "Project",
    "ProjectThread",
    "Property",
    "PropertyBase",
    "PropertyControlType",
    "PropertyGroup",
    "PropertyType",
    "PropertyValueType",
    "ProxyUseSetting",
    "PulldownMethod",
    "PulldownPhase",
    "PulldownSetting",
    "PurgeTarget",
    "RenderQuality",
    "RenderQueue",
    "RenderQueueItem",
    "SettingsView",
    "ResizeQuality",
    "ResolveType",
    "RQItemStatus",
    "Shape",
    "ShapeLayer",
    "SolidSource",
    "SoloSwitchesSetting",
    "TargaFormatOptions",
    "TextDocument",
    "TextLayer",
    "ThreeDModelLayer",
    "TiffFormatOptions",
    "TimeDisplayType",
    "TimeSpanSource",
    "ToolType",
    "TrackMatteType",
    "View",
    "Viewer",
    "ViewerType",
    "ViewOptions",
    "XmlFormatOptions",
]


def parse(aep_file_path: str | os.PathLike[str]) -> Application:
    """Parse an After Effects (.aep) project file and return an [Application][] instance.

    This is the main entry point for the library. It parses the binary
    RIFX data and returns an [Application][] object whose
    [project][py_aep.models.application.Application.project] attribute
    holds the full project tree.

    Args:
        aep_file_path: Path to the `.aep` file.

    Example:
        ```python
        import py_aep

        app = py_aep.parse("project.aep")
        project = app.project
        print(app.version)
        ```
    """
    from .kaitai.proxy import _suppress_materialization
    from .parsers.application import parse_app
    from .parsers.project import parse_project

    file_path = os.fspath(aep_file_path)
    with _suppress_materialization(), Aep.from_file(file_path) as aep:
        aep._read()
        project = parse_project(aep, file_path)
        return parse_app(aep, project)
