"""`read_ai_layer_bounds` against After Effects' own artwork boxes.

Both fixtures are AE 2026 imports, so these tests compare py_aep's measuring
pass against the real thing rather than against expectations:

- `ai_bounds_probe.aep` is a `COMP_CROPPED_LAYERS` import of the hand-built
  `ai_bounds_probe.pdf` (one layer per rule, regenerated by
  `scripts/make_ai_bounds_probe.py`);
- `ai_choose_layer1_size.aep` is a Choose Layer + Layer Size **footage** import
  of a real Illustrator file, which is what `layer_dimensions="layer"`
  actually produces. The two paths store the same box, which is what licenses
  using the cropped comp as the oracle;
- `std14_probe.aep` is a `COMP_CROPPED_LAYERS` import of `std14_probe.pdf`,
  whose every layer draws from a font dictionary carrying neither `/Widths`
  nor a `/FontDescriptor`, so AE has nothing but its built-in standard-14
  metrics to measure with. Two layers per font draw a single glyph, and a
  third draws every tabulated code at once, so its width is the sum of all 95
  advances.
"""

from __future__ import annotations

import warnings
from functools import lru_cache
from pathlib import Path

import pytest
from helpers import ai_layer_opti_boxes, parse_project

from py_aep.resolvers.ai_bounds import EMPTY_BOX, footage_size, read_ai_layer_bounds
from py_aep.resolvers.ai_layers import read_ai_layers

ASSETS = Path(__file__).parent.parent.parent / "samples" / "assets"
IMPORT_DIR = Path(__file__).parent.parent.parent / "samples" / "models" / "import"

PROBE_PDF = ASSETS / "ai_bounds_probe.pdf"
PROBE_AEP = IMPORT_DIR / "ai_bounds_probe.aep"

STD14_PDF = ASSETS / "std14_probe.pdf"
STD14_AEP = IMPORT_DIR / "std14_probe.aep"

#: After Effects' own arithmetic differs from ours in the last fixed-point
#: step or two, so a handful of layers land within a couple of 1/65536
#: quanta (0.00003pt) rather than exactly. Every derived footage dimension
#: still matches, which is what the stored box is actually used for.
QUANTUM = 1 / 65536
TOLERANCE = 3 * QUANTUM


@lru_cache(maxsize=None)
def _ae_layer_boxes(aep: Path) -> dict[str, tuple[tuple[float, ...], int, int]]:
    """After Effects' own artwork box and footage size, per layer name."""
    return ai_layer_opti_boxes(parse_project(aep))


@lru_cache(maxsize=None)
def _measured(path: Path) -> dict[str, tuple[float, ...] | None]:
    """Every layer's measured box, read and measured once per file."""
    data = path.read_bytes()
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        names = read_ai_layers(path, data)
        bounds = read_ai_layer_bounds(path, data)
    return dict(zip(names, bounds))


def _probe_layers() -> list[str]:
    return list(_ae_layer_boxes(PROBE_AEP))


def _std14_layers() -> list[str]:
    return list(_ae_layer_boxes(STD14_AEP))


class TestProbeFixture:
    """Every rule, against the AE import of the hand-built probe PDF."""

    def test_every_layer_is_measured(self) -> None:
        measured = _measured(PROBE_PDF)
        assert set(measured) == set(_ae_layer_boxes(PROBE_AEP))
        assert len(measured) == 22

    @pytest.mark.parametrize("layer", _probe_layers())
    def test_box_matches_after_effects(self, layer: str) -> None:
        ae_box, _width, _height = _ae_layer_boxes(PROBE_AEP)[layer]
        box = _measured(PROBE_PDF)[layer]
        expected = EMPTY_BOX if box is None else box
        assert expected == pytest.approx(ae_box, abs=TOLERANCE)

    @pytest.mark.parametrize("layer", _probe_layers())
    def test_derived_footage_size_matches_after_effects(self, layer: str) -> None:
        _box, width, height = _ae_layer_boxes(PROBE_AEP)[layer]
        assert footage_size(_measured(PROBE_PDF)[layer]) == (width, height)

    def test_layer_with_no_artwork_measures_empty(self) -> None:
        assert _measured(PROBE_PDF)["q_empty"] is None

    def test_most_layers_are_byte_exact(self) -> None:
        # A guard on the float divergence above: if a change starts rounding
        # differently across the board, this drops well below the current 19.
        ae = _ae_layer_boxes(PROBE_AEP)
        measured = _measured(PROBE_PDF)
        exact = 0
        for name, (ae_box, _w, _h) in ae.items():
            box = measured[name]
            raw_py = tuple(
                round(v * 65536) for v in (EMPTY_BOX if box is None else box)
            )
            raw_ae = tuple(round(v * 65536) for v in ae_box)
            exact += raw_py == raw_ae
        assert exact >= 19


class TestIllustratorFootageFixture:
    """The real-Illustrator case, against AE's Layer Size footage import."""

    def test_box_matches_the_footage_import(self) -> None:
        # `ai.ai`'s Calque 1 is a bezier clip filled by a shading plus a
        # rotated five-glyph text run: its box takes the minimum corner from
        # the unpadded text and the maximum from the padded path, which is
        # what pins the expansion as per-contribution.
        ae = _ae_layer_boxes(IMPORT_DIR / "ai_choose_layer1_size.aep")
        box = _measured(ASSETS / "ai.ai")["Calque 1"]
        assert box == pytest.approx(ae["Calque 1"][0], abs=TOLERANCE)
        assert footage_size(box) == (482, 437)

    def test_empty_layer_matches_the_footage_import(self) -> None:
        ae = _ae_layer_boxes(IMPORT_DIR / "ai_choose_layer_size.aep")
        assert ae["Calque 2"][0] == pytest.approx(EMPTY_BOX, abs=TOLERANCE)
        assert _measured(ASSETS / "ai.ai")["Calque 2"] is None

    def test_cropped_comp_and_footage_paths_agree(self) -> None:
        # The cropped-comp import is the oracle the rules were measured
        # against; this is the check that licenses it.
        cropped = _ae_layer_boxes(IMPORT_DIR / "ai_comp.aep")
        footage = _ae_layer_boxes(IMPORT_DIR / "ai_choose_layer.aep")
        # Both are Document Size imports of the same file, so both store the
        # full-page box.
        assert cropped["Calque 1"][0] == pytest.approx((0.0, 0.0, 612.0, 792.0))
        assert footage["Calque 2"][0] == pytest.approx((0.0, 0.0, 612.0, 792.0))


class TestStandard14Fixture:
    """The built-in font metrics, against AE's import of the font probe.

    Every layer draws from a font dictionary with no `/Widths` and no
    `/FontDescriptor`, so nothing in the file says how wide or how tall the
    text is and only `data.std14_metrics` can supply it.
    """

    def test_every_layer_is_measured(self) -> None:
        measured = _measured(STD14_PDF)
        assert set(measured) == set(_ae_layer_boxes(STD14_AEP))
        assert len(measured) == 48

    @pytest.mark.parametrize("layer", _std14_layers())
    def test_box_matches_after_effects(self, layer: str) -> None:
        ae_box, _width, _height = _ae_layer_boxes(STD14_AEP)[layer]
        assert _measured(STD14_PDF)[layer] == pytest.approx(ae_box, abs=TOLERANCE)

    @pytest.mark.parametrize("layer", _std14_layers())
    def test_derived_footage_size_matches_after_effects(self, layer: str) -> None:
        _box, width, height = _ae_layer_boxes(STD14_AEP)[layer]
        assert footage_size(_measured(STD14_PDF)[layer]) == (width, height)

    def test_every_layer_is_byte_exact(self) -> None:
        # Unlike the geometry probe, nothing here goes through the expansion
        # arithmetic that costs the odd fixed-point quantum, so these should
        # match After Effects to the bit.
        ae = _ae_layer_boxes(STD14_AEP)
        measured = _measured(STD14_PDF)
        for name, (ae_box, _w, _h) in ae.items():
            box = measured[name]
            assert box is not None
            raw_py = tuple(round(v * 65536) for v in box)
            assert raw_py == tuple(round(v * 65536) for v in ae_box), name

    def test_aliases_measure_as_their_standard_14_face(self) -> None:
        # AE resolves /Arial and /TimesNewRoman onto its built-in Helvetica
        # and Times-Roman metrics rather than onto the installed face, which
        # is the evidence that the tables are not host-specific.
        measured = _measured(STD14_PDF)
        for alias, face in (("Arial", "Helvetica"), ("TimesNewRoman", "Times-Roman")):
            for prefix in ("A", "B", "C"):
                alias_box = measured[f"{prefix}_{alias}"]
                face_box = measured[f"{prefix}_{face}"]
                assert alias_box is not None and face_box is not None
                assert (
                    alias_box[2] - alias_box[0],
                    alias_box[3] - alias_box[1],
                ) == pytest.approx(
                    (face_box[2] - face_box[0], face_box[3] - face_box[1])
                )
